# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('height', models.IntegerField(max_length=100, unique=True)),
                ('live', models.TextField(max_length=100)),
            ],
        ),
    ]
