# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonInfoSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='live',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=10, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.IntegerField(max_length=200, unique=True),
        ),
    ]
