# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonInfoSite', '0002_auto_20170715_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
