# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='First_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UFirst_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Last_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ULast_Name', models.CharField(max_length=30)),
            ],
        ),
    ]
